package Modelo;
// Generated 03-jun-2021 19:26:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *Personajes generated by hbm2java
 */
public class Personajes implements java.io.Serializable {


     private int idp;
     private String nombrep;
     private int costep;
     private String rol;
     private Date lanzamientop;

    public Personajes() {
    }

    public Personajes(int idp, String nombrep, int costep, String rol, Date lanzamientop) {
       this.idp = idp;
       this.nombrep = nombrep;
       this.costep = costep;
       this.rol = rol;
       this.lanzamientop = lanzamientop;
    }
   
    public int getIdp() {
        return this.idp;
    }
    
    public void setIdp(int idp) {
        this.idp = idp;
    }
    public String getNombrep() {
        return this.nombrep;
    }
    
    public void setNombrep(String nombrep) {
        this.nombrep = nombrep;
    }
    public int getCostep() {
        return this.costep;
    }
    
    public void setCostep(int costep) {
        this.costep = costep;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Date getLanzamientop() {
        return this.lanzamientop;
    }
    
    public void setLanzamientop(Date lanzamientop) {
        this.lanzamientop = lanzamientop;
    }




}


