package Modelo;
// Generated 03-jun-2021 19:26:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 *Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idu;
     private String usu;
     private String contra;
     private String apodo;
     private String telefono;
     private String email;
     private Date diaalta;

    public Usuarios() {
    }

    public Usuarios(int idu, String usu, String contra, String apodo, String telefono, String email) {
       this.idu = idu;
       this.usu = usu;
       this.contra = contra;
       this.apodo = apodo;
       this.telefono = telefono;
       this.email = email;
 
    }
   
    public int getIdu() {
        return this.idu;
    }
    
    public void setIdu(int idu) {
        this.idu = idu;
    }
    public String getUsu() {
        return this.usu;
    }
    
    public void setUsu(String usu) {
        this.usu = usu;
    }
    public String getContra() {
        return this.contra;
    }
    
    public void setContra(String contra) {
        this.contra = contra;
    }
    public String getApodo() {
        return this.apodo;
    }
    
    public void setApodo(String apodo) {
        this.apodo = apodo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDiaalta() {
        return this.diaalta;
    }
    
    public void setDiaalta(Date diaalta) {
        this.diaalta = diaalta;
    }




}


